include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:


analyzer:
  exclude:
    # Codegen
    - 'lib/**.gen.dart'
    - 'lib/**.g.dart'
    - 'lib/**.freezed.dart'
    # Build
    - 'build/**'
    # Tests
    - 'test/**.mocks.dart'
    - '.test_coverage.dart'
    # Assets
    - 'assets/**'
#linter:
#  rules:
